config/routes.rb
Cascading::Application.routes.draw do

  
  resources :users do
    collection do
      get :update_areas
      get :update_neighborhoods
    end
  end
  
  root :to => 'users#new'
  

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :neighborhoods
  
  belongs_to :city
  
  # attr_accessible :title, :body
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :areas
  
  # attr_accessible :title, :body
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  
  belongs_to :area
  
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    
    @cities = City.all
    @areas = []
    @neighborhoods = []
    
  end

  def create
  end

  def edit
  end

  def update
  end

  def destory
  end
  
  
   def update_areas
    city_id =  (params[:city_id].nil? || params[:city_id].empty?) ? 0 : params[:city_id].to_i
     
      # updates artists and songs based on genre selected
      if city_id == 0
        @areas = []
        @neighborhoods = []
        
      else
        city = City.find(params[:city_id])
        # map to name and id for use in our options_for_select
        @areas = city.areas.map{|a| [a.name, a.id]}
        @neighborhoods = Neighborhood.where(:area_id => city.areas.each{|a| a.id}).map{|s| [s.name, s.id]}
        
      end
      
      @areas.insert(0, "Select an Area")
      @neighborhoods.insert(0, "Select a neighborhood") 
      
      
    end

    def update_neighborhoods
      # updates songs based on artist selected
      area = Area.find(params[:area_id])
      @neighborhoods = area.neighborhoods.map{|s| [s.name, s.id]}.insert(0, "Select a neighborhood")
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cascading</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<% @users.each  do |u| %>
  <p>name: u.name</p>
<%end%>

<%= link_to 'new', new_user_path %>

app/views/users/new.html.erb
<script>
$(document).ready(function() {
$('#cities_select').change(function() {
  $.ajax({
    url: "<%= update_areas_users_path %>",
    data: {
      city_id : $('#cities_select').val()
    },
    dataType: "script"
  });
});

$('#areas_select').change(function() {
  $.ajax({
    url: "<%= update_neighborhoods_users_path(@user) %>",
    data: {
      area_id : $('#areas_select').val()
    },
    dataType: "script"
  });
});

});
</script>



<%= form_for @user do |f| %>
  <p>name: <%= f.text_field :name %> </p>

  <p>City:</p>
    <%= f.collection_select(:city_id,  @cities,  :id, :name, {:prompt   => "Select a City"}, {:id => 'cities_select'}) %>

    <p>City area:</p>
    <%= f.collection_select(:area_id, @areas, :id, :name, {:prompt   => "Select an Area"}, {:id => 'areas_select'}) %>

    <p>Neighborhood:</p>
    <%= f.collection_select(:neighborhood_id, @neighborhoods, :id, :name, {:prompt   => "Select a Neighborhood"}, {:id => 'neighborhoods_select'}) %>
  
<%end%>

    

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update_areas.js.erb
$('#areas_select').html("<%= escape_javascript(options_for_select(@areas)) %>");
$('#neighborhoods_select').html("<%= escape_javascript(options_for_select(@neighborhoods)) %>");

app/views/users/update_neighborhoods.js.erb
$('#neighborhoods_select').html("<%= escape_javascript(options_for_select(@neighborhoods)) %>");